### PR TITLE
Add js-dev task to Gulp

### PR DESCRIPTION
**Pull request by remexre**
This task builds without minification or automatic es6 inclusion, instead we straight-up concat the deps in.

### CODE REVIEW

**Comment by remexre** [comment]
Which reminds me, we should probably actually concat the deps...

**Comment by remexre** [comment]
Assuming performance on non-dev builds isn't an issue, I think it's ok to merge this?

**Comment by remexre** [comment]
My Pixel:

| Branch | Target | Build Time |
| --- | --- | --- |
| master | js | 14.16s |
| gulp-js-dev | js | 11.21s |
| gulp-js-dev | js-dev | 2.34s |

Weirdly, I feel like the master `gulp js` performance was better in the past? <10sec, at least.

**Comment by akshay288** [comment]
My Desktop

| Branch | Target | Build Time |
| --- | --- | --- |
| master | js | 10.79s |
| gulp-js-dev | js | 7.82s |
| gulp-js-dev | js-dev | 1.58s |

**Comment by remexre** [comment]
Okay, so if it improves performance on all sides for both of us, should I merge?

**Pull request merged**
